# Generated by Django 3.2.3 on 2021-05-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='upload',
        ),
    ]
