# Generated by Django 3.2.3 on 2021-05-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_rename_file_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='slug',
        ),
    ]
