# Generated by Django 3.2.3 on 2021-05-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20210526_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.filehash'),
        ),
    ]
